## Site settings
# title, shows up in browser title bar
title: MLV Lab
# description shows up in site meta data, for search engines
description: |
  Machine Learning and Vision Lab at Zhejiang Normal University.

favicon:
  small: /logos/mlv-logo.png
  medium: /logos/mlv-logo.png
  apple_touch_icon: /logos/mlv-logo.png
  safari_pinned_tab: /logos/mlv-logo.png
  #android_manifest: /logos/mlv-logo.png

# baseurl is used to format links in jekyll
baseurl: ""
# url is the sites full domain name
url: "http://zjnu-mlv-lab.github.io/"
# nice and clean blog URLs
permalink: "/blog/:title.html"
# name is used in the page header
name: MLV Lab


## default site author info
# author is the name below posts
author: Dawei Zhang
# author-url links this name to another page, twitter etc
author-url: https://davidzhangdw.github.io/

## this prevents jekyll from building pages that are not website pages, but repo only pages
exclude: ["README.md", "CODEOFCONDUCT.md"]

## pagination settings
# set the total number of posts per page for the blog
paginate: 4
# have posts paged as: /blog/page2, /blog/page3 etc
paginate_path: "/blog/:num/"
